spring:
  application:
    name: drone-delivery-service
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: drone
        format_sql: true
    show-sql: "${SHOW_SQL:false}"
  datasource:
    url: "jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:drone}"
    driver-class-name: org.postgresql.Driver
    username: "${DB_USER:postgres}"
    password: "${DB_PASSWORD:password}"
  flyway:
    enabled: true
    schemas: drone
    create-schemas: true
    baseline-version: 1

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

audit:
  drone:
    cron: "*/30 * * * * *" # every 30 seconds

