ktor:
  application:
    modules:
      - com.github.chMatvey.ApplicationKt.module
  deployment:
    port: 8080

database:
  type: postgresql
  driverClassName: org.postgresql.Driver
  jdbcUrl: "jdbc:postgresql://localhost:5432/drone"
  username: postgres
  password: password
  schema: drone
